<?php

/**
 * ReportMapper - Sales and Marketing Reporting Tool for Magento 1x
 * @category ReportMapper
 * @package	ReportMapper_SalesReportMaps
 * @version	1.0.0
 * @created	10th January 2018 3.00pm
 * @author	Paul Watt <support@reportmapper.com>
 * @purpose	ReportMapper block
 * @copyright	Copyright (c) 2018 ReportMapper.com
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License
 */

    $path_data = $this->getPaths();
    $label_data = $this->getLabels();
    $map_labels = $this->getMapLabeling();
    $table_data = $this->getTables();
    $svg_data = $this->getSVG();
?>
<h1><?php echo $svg_data['svg_header']; ?> <input value="Print Report" class="map_form_button submit required-entry" type="submit" onClick="window.print()"></h1>
<svg id="<?php echo $svg_data['svg_id']; ?>" xmlns="<?php echo $svg_data['svg_xmlns']; ?>" version="<?php echo $svg_data['svg_version']; ?>" width="<?php echo $svg_data['svg_width']; ?>" height="<?php echo $svg_data['svg_height']; ?>" transform="<?php echo $svg_data['svg_transform']; ?>" viewBox="<?php echo $svg_data['svg_viewbox']; ?>" viewPort="<?php echo $svg_data['svg_viewport']; ?>">
    <g transform="<?php echo $svg_data['svg_g_transform']; ?>">
        <?php
        foreach($path_data['path_results'] as $path_result)
        {
            $path = $path_result['path'];
            $areacode = strtoupper($path_result['postcode']);
            $aa = $path_result['aa'];
            $colour_results = $this->getOpaqueness($aa,$path_data['path_max_aa']);
            $opacity=$colour_results['opacity'];
            ?>
                <path d="<?php echo $path; ?>" fill="#FFF"/>
                <path d="<?php echo $path; ?>" id="<?php echo $areacode; ?>" fill="<?php echo $path_data['path_map_colour'] ?>" fill-opacity="<?php echo $opacity; ?>" stroke="#000000" stroke-width="<?php echo $path_result['stroke_width']; ?>" stroke-opacity="1" fill-rule="evenodd" name_kml="<?php echo $areacode; ?>" onmouseover="show(evt, 'label_<?php echo $areacode; ?>','<?php echo $path_data['path_highlight_colour'] ?>')" onmouseout="hide(evt, 'label_<?php echo $areacode; ?>','<?php echo $path_data['path_map_colour'] ?>')"/>
            <?php
        }
        ?>
    </g>
    <g class="labels" transform="<?php echo $svg_data['svg_g_labels_transform']; ?>">
        <?php
        foreach ($map_labels as $lable) {
            ?><text visibility="visible" class="<?php echo $lable['postcode']; ?>" transform="matrix(<?php echo $lable['text_path'];?>)" font-size="<?php echo $lable['text_size']?>"><?php echo $lable['postcode'];?></text>
            <?php
        }
        ?>
    </g>
</svg>
<div class="clearfix"></div>
<div class="page-break"></div>

<?php
    foreach($label_data['label_results'] as $label_result)
    {
    $area_code = strtoupper($label_result['pc']);?>
      <div id="label_<?php echo $area_code; ?>" class="label_pc">
        <ul class="salesdata">
        <li><h1><?php echo $area_code; ?> <?php echo $label_data['label_h1']; ?></h1></li>
        <li><div><div class="productlabel"><?php echo $label_data['label_aa_header']; ?></div><div class="aalabel"><?php echo $label_data['label_bb_header']; ?></div></div></li>
            <?php
            $label_items = $this->getLabelItems($area_code);
            $i = 0;
            foreach($label_items as $item)
            {
                $item_aa = $item['label_aa'];
                $item_bb = $item['label_bb'];
                if (0 == $i % 2){
                    $rowcolour = "resultrowodd";
                }else{
                    $rowcolour = "resultroweven";
                }
                $i++;
                ?>
        <li><div class="<?php echo $rowcolour; ?>"><div class="product"><?php echo $item_aa; ?></div><div class="aa"><?php echo $label_data['currencyA'].$item_bb; ?></div></div></li>
        <?php } ?>
        </ul>
      </div>
<?php } ?>

<div class="postcode_outer_div">
    <div class="postcode_div">
        <div class="row_col_header">Strength</div>
        <div class="row_area_header">Area</div>
        <div class="row_a_header"><?php echo $table_data['table_row_aa_header']; ?></div>
        <div class="row_b_header"><?php echo $table_data['table_row_bb_header']; ?></div>
        <?php
        $i = 0;
        foreach($table_data['table_results'] as $table_result)
        {
            if (0 == $i % 2){
                $rowcolour = "row_div_odd";
            }else{
                $rowcolour = "row_div_even";
            }
            $areacode = strtoupper($table_result['postcode']);
            $aa = $table_result['aa'];
            $bb = round($table_result['bb'],2);
            if($aa ==0){
                $aa = null;
            }
            $colour_results = $this->getOpaqueness($aa,$table_data['table_max_aa']);
            $opacitycss=$colour_results['opacitycss'];
            $aa=$colour_results['aa'];
            ?>
        <div class="<?php echo $rowcolour; ?>" id="divrow_<?php echo $areacode; ?>" onmouseover="ChangeBackgroundColor(this,'<?php echo $table_data['table_highlight_colour']; ?>')" onmouseout="RestoreBackgroundColor(this,'<?php echo $table_data['table_map_colour']; ?>','<?php echo $rowcolour; ?>')">
        <div class="bgcol" style="background-color:<?php echo $table_data['table_map_colour']; ?> !important;"><div style="opacity:<?php echo $opacitycss; ?>; background:white !important; width:50px; height:25px; margin:0px;"></div></div>
        <div class="row_area"><?php echo $areacode; ?></div>
        <div class="row_a"><?php echo $table_data['table_currencyA'] ?><?php echo $aa; ?></div>
        <div class="row_b"><?php echo $table_data['table_currencyB'] ?><?php echo $bb; ?></div>
        </div>
        <?php
            $i++;
            if($i  % 34 == 0){
                ?>
    </div>
     <div class="postcode_div" width="200px">
         <div class="row_div">
             <div class="row_col_header">Strength</div>
             <div class="row_area_header">Area</div>
             <div class="row_a_header"><?php echo $table_data['table_row_aa_header']; ?></div>
             <div class="row_b_header"><?php echo $table_data['table_row_bb_header']; ?></div></div>
     <?php
            $i = 0;
            }
        }
        ?>
    </div>
</div>
<p class="rm_footer"><?php echo $svg_data['svg_footer']; ?></p>
<?php echo $this->getLicenceValidation(); ?>